[build]
target = "x86_64-rustos.json"

[unstable]
# Use built-in mem related C functions.
build-std-features = ["compiler-builtins-mem"]
# Cargo should recompile `core` and `compiler_builtins` libraries.
# Run `rustup component add rust-src` to download the source code of the libs.
build-std = ["core", "compiler_builtins"]

